#!/bin/sh
#
# Copyright 2004 The Apache Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# A (supposedly ) friendly commandline interface to the common gump tasks
#
##############################################################################
# Documentation
##############################################################################

# Documentation for the different commands.
function usage
{
  case $1 in
    help-variables)
      echo "
      Gump needs various other programs available in order to run. You
      can change which programs gump tries to use using environment variables.
      In addition, several core gump settings are also customizable using
      environment variables.
      
      You can set all these variables (except for GUMP_HOME) in the file
      
        $GUMP_ENV_FILE
      
      the location of this file is found as follows:
      
        GUMP_HOME/GUMP_HOST-settings.sh
      
      Recognized variables are:
      
        GUMP_HOME     -- location of the gump subversion checkout. Defaults
                         to the current working directory if possible.
        GUMP_HOSTNAME -- name of this machine. Defaults to the output from the
                         hostname command.
        GUMP_ENV_FILE -- location of the file that contains the custom
                         settings to load (i.e. the file mentioned above). You
                         can override GUMP_HOME and GUMP_HOSTNAME here, but that
                         may have some unpredictable effects.
        GUMP_PYTHON   -- the name of the python executable to use. Defaults to
                         the latest version of python that is installed. Note
                         that pygump is supported only on python2.3.
        JAVA_HOME     -- the location of a java development kit. Gump tries to
                         work with any JDK, but results may vary (for example,
                         both ant and maven require jdk 1.2 at least).
        
      These varialbes are only used by dynagump:

        JAVA_OPTIONS  -- Extra options to pass to the JVM.
        JETTY_PORT    -- Override the default port for Jetty. Defaults to 8080.
        JETTY_ADMIN_PORT -- The port where the jetty web administration should
                         bind. Defaults to 8081.
        JAVA_DEBUG_PORT -- The port the JVM debug server should listen to.
                         Defaults to 8082.
"
    run)
      echo "
      Run Pygump.

      Usage:
        $0 run [gump.py-args ...]

      See http://wiki.apache.org/gump/GumpCommandLineOptions for more
      information about the options pygump accepts. The one mandatory
      argument is the "project expression" detailing what to run. You
      will usually want "all" here.
"
        ;;
    debug)
      echo "
      Run pygump in debug mode.
      
      Usage:
        $0 debug [gump.py-args ...]
    
      This is the same as executing the 'run' command with a '--debug'
      parameter.
"
        ;;
    test)
      echo "
      Run pygump its unit tests.

      Usage:
        $0 test
"
        ;;
    dynagump)
      echo "
      Run Dynagump.

      Usage:
        $0 dynagump dynagump-action [dynagump-args ...]

      Run
        $0 dynagump help
      for more information about the options dynagump accepts. If no action is
      specified, gump passes run as the action to execute.
"
        ;;
    create-database)
      echo "
      Create a new MySQL database with the gump database schema.

      Usage:
        $0 create-database [database-name] [mysql-args ...]

      If no database-name is specified, gump will assume the database should
      be named "gump". All other provided arguments are passed on to mysql, so
      if you need to connect using a different username and password you can
      do so, for example
      
        $0 create-database gump -u gump -p password_for_gump_user
      
      This command will fail if the specifed database already exists.
"
        ;;
    *)
      echo "
      Utility commandline interface for Gump.
     
      Usage:
        $0 command [opts ...]
     
      Available commands are:
     
        run -- run pygump
        debug -- run pygump in debug mode
        test -- run the pygump unit tests
     
      Run
     
        $0 help [command]
     
      for more information about a particular command.
      
      Run
      
        $0 help-variables
      
      for more information about the environment variables that alter gump its
      behaviour.
"
        ;;
  esac
}

##############################################################################
# Setup methods
##############################################################################
# All of these are guaranteed to have run before any other method is
# called, so other methods may safely assume that the basic environment
# these methods put in place is there.

# Determine the short form of the hostname
function find_hostname
{
  if [[ ! -z "$GUMP_HOSTNAME" ]]; then
    return
  fi
  
  local hostnamecommand=`which hostname`
  if [[ ! -z "$hostnamecommand" ]]; then
    error "GUMP_HOSTNAME is not set and the hostname command is not
available to determine it!"
  fi
  
  local cygwin=false;
  case "`uname`" in
    CYGWIN*) cygwin=true ;;
  esac
  if $cygwin; then
    export GUMP_HOSTNAME=`hostname`
  else
    export GUMP_HOSTNAME=`hostname -s`
  fi
}

# Determine the location gump is installed in
function find_home
{
  if [[ ! -z "$GUMP_HOME" ]]; then
    return
  fi
  
  # look for this file
  local current=`pwd`
  local thisscript="`pwd`/gump"
  if [[ -f "$thisscript" ]]; then
    # guess...
    export GUMP_HOME="$current"
  else
    # complain!
    error "GUMP_HOME is not set and failed to determine it. Please set it to
the root of your svn checkout!"
  fi
}

# Determine the location of the environment variables script
function find_env_file
{
  export GUMP_ENV_FILE="$GUMP_HOME/$GUMP_HOSTNAME-settings.sh"
}

# Determine the python command to use
function find_python
{
  if [[ ! -z "$GUMP_PYTHON ]]; then
    return
  fi

  local python=`which python2.4`
  if [[ -z "$python" ]]; then
    python=`which python2.3`
  fi
  if [[ -z "$python" ]]; then
    python=`which python2`
  fi
  if [[ -z "$python" ]]; then
    python=`which python`
  fi
  if [[ -z "$python" ]]; then
    python="python" # hope for the best...
  fi
  
  export GUMP_PYTHON="$python"
}

# Load the environment variables script if it exists, then fill out missing
# but required variables
function setup_env
{
  find_hostname
  find_home

  find_env_file
  if [[ -f "$GUMP_ENV_FILE" ]]; then
    . "$GUMP_ENV_FILE"
  fi
  
  find_python
}

##############################################################################
# Utility functions
##############################################################################
# These functions don't represent actual commands but rather are utilized
# from the command functions.

# Print an error message and then exit.
function error
{
  echo "$0: $1"
  exit 1
}

# Print a friendly error message if some dependency is missing.
#
# Arguments:
#   - name of the command
#   - url to download the package that provides it
function check_command
{
  local cmd=`$GUMP_HOME/bin/PrintPath $1`;
  if [[ -z "$cmd" ]]; then
     error "Cannot find $1. Please retrieve it from 

     $2
     
and install it. If it is already installed, modify your $PATH variable
to point to it. You can customize the $PATH variable inside a file named
  $GUMP_ENV_FILE
if you wish."
  fi
}

# Print a friendly error message if an environment variable is not set.
#
# Arguments:
#   - name of the variable
#   - description of what the variable should be set to
function check_env_var
{
  local dereferenced="${!1}"
  if [[ -z "$dereferenced" ]]; then
    error "The variable $1 has not been set. It should be set to
$2.
You can either set this before invoking gump, or set it in a file
named
  $GUMP_ENV_FILE
if you wish."
  fi
}

# Print a friendly error message i a python library is not available.
#
# Arguments:
#   - the library to import
#   - url to download location of the library
function check_pylib
{
  cat > "$GUMP_HOME/pycmd.tmp.py" <<ENDCOMMAND
try:
  import $1
except:
  print "error"
ENDCOMMAND
  local cmd=`$GUMP_PYTHON "$GUMP_HOME/pycmd.tmp.py"`
  result=`$cmd`
  rm -f "$GUMP_HOME/pycmd.tmp.py"

  if [[ ! -z "$result" ]]; then
    error "Required python library $1 is not available.
Please download it from

  $2

and install it."
  fi
}

# Print a friendly error message if the environment is not set up correctly.
function check_environment
{
  check_command "$GUMP_PYTHON" "http://www.python.org/"
  check_command "pkill" "http://sourceforge.net/projects/proctools"
  check_command "mysql" "http://www.mysql.com/"
  check_command "mysqladmin" "http://www.mysql.com/"

  check_env_var "JAVA_HOME" "the location of the java jdk"
  
  check_pylib "rdflib" "http://rdflib.net/"
  check_pylib "MySQLdb" "http://sourceforge.net/projects/mysql-python"
}

#############################################################################
# Action functions
#############################################################################
# There is one of these for each command that gump understands. Stricly
# speaking, the usage function above is also an action function, but we put
# it at the top of the file for readability :-D

# Run pygump
function run
{
  # add pygump to python path
  local oldpythonpath="$PYTHONPATH"
  if [[ -z "$oldpythonpath" ]]; then
    export PYTHONPATH="$GUMP_HOME/pygump/python:$GUMP_HOME/pygump"
  else
    export PYTHONPATH="$GUMP_HOME/pygump/python:$GUMP_HOME/pygump:$PYTHONPATH"
  fi

  # run pygump
  local current=`pwd`
  cd "$GUMP_HOME/pygump"
  $GUMP_PYTHON gump.py $*
  cd "$current"

  # restore python path
  if [[ ! -z "$oldpythonpath" ]]; then
    export PYTHONPATH="$oldpythonpath"
  fi
}

# Run pygump unit tests
function test
{
  # add pygump to python path
  local oldpythonpath="$PYTHONPATH"
  if [[ -z "$oldpythonpath" ]]; then
    export PYTHONPATH="$GUMP_HOME/pygump/python:$GUMP_HOME/pygump"
  else
    export PYTHONPATH="$GUMP_HOME/pygump/python:$GUMP_HOME/pygump:$PYTHONPATH"
  fi

  # Run the pygump tests
  local current=`pwd`
  cd "$GUMP_HOME/pygump/python"
  python ../../bin/testrunner.py -d ../python/gump/test $@
  cd "$current"
  
  # restore python path
  if [[ ! -z "$oldpythonpath" ]]; then
    export PYTHONPATH="$oldpythonpath"
  fi
}

# Run dynagump
function dynagump
{
  # "run" is the default command
  local command="$1"
  shift
  if [[ -z "$command" ]]; then
    $command="run"
  fi
  
  local current=`pwd`
  cd "$GUMP_HOME/dynagump"
  ./dynagump.sh $command $@
  cd "$current"
}

function create_database
{
  local db="$1"
  shift
  if [[ -z "$db" ]]; then
    db="gump"
  fi
  
  # this will also ensure we don't delete an existing database since the
  # create command will fail
  local mysqladminresult=`mysqladmin create "$db" $@`
  if [[ ! -z "$mysqladminresult" ]]; then
    error "Gump failed to create the database $db. mysqladmin said:

$mysqladminresult"
  fi
  
  local mysqlresult=`mysql create "$db" $@ <
    $GUMP_HOME/gumpdb/src/sql/gump3-database-definition.sql`
  
  if [[ ! -z "$mysqlresult" ]]; then
    error "Gump failed to populate the database $db. mysql said:

$mysqlresult"
  fi
}

#############################################################################
# Main
#############################################################################
# Control logic and program flow are defined below.

# Figure out which action to execute.
function delegate
{
  local called_as="$0"
  local command="$1"
  shift

  if [[ -z "$command" ]]; then
    error "Illegal command '$command'"
  fi

  # delegate to the command handling functions
  case $command in

    run)
      run $@
      ;;
    debug)
      run --debug $@
      ;;
    test)
      test $@
      ;;
    dynagump)
      dynagump $@
      ;;
    create-database)
      create-database $@
      ;;
    help* | usage | --help | -help | -H | -h)
      usage $@
      ;;
    '')
      error "Please specify a command"
      ;;
    *)
      error "Unknown command '$command'"
      ;;
  esac
}

# Load environment variables
setup_env

# Check we have everything we need
check_environment

# Figure out the action to take then run the appropriate function
delegate $@

# Attempt to clean up leftover commands
pkill -KILL -P $$
